# Generated by Django 4.1.5 on 2023-04-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
