# Generated by Django 4.1.5 on 2023-04-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_delete_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tablenumber',
        ),
    ]
