# Generated by Django 4.1.5 on 2023-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('tablenumber', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('itemname', models.CharField(max_length=60)),
                ('itemquantity', models.IntegerField()),
                ('itemprice', models.IntegerField()),
                ('total', models.IntegerField()),
                ('orderstatus', models.CharField(default='waiting', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('tablenumber', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
