# Generated by Django 4.1.5 on 2023-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
