# Generated by Django 4.1.5 on 2023-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_orders_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(blank=True, default='waiting', max_length=20, null=True),
        ),
    ]
