# Generated by Django 4.1.5 on 2023-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_delete_orderconform'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cook',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
    ]
