# Generated by Django 4.1.5 on 2023-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_orders_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='customercall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablecall', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
