# Generated by Django 4.1.5 on 2023-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_customercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(blank=True, default='notpaid', max_length=25, null=True),
        ),
    ]
