# Generated by Django 4.1.5 on 2023-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_orders_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=20)),
            ],
        ),
    ]
