# Generated by Django 4.1.5 on 2023-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_tablenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancel',
            field=models.CharField(blank=True, default='No', max_length=20, null=True),
        ),
    ]
