# Generated by Django 4.1.5 on 2023-04-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_orders_cancel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tablenumber',
        ),
    ]
